/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_smartapp_update_BatchUtils */

#ifndef _Included_com_smartapp_update_BatchUtils
#define _Included_com_smartapp_update_BatchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_smartapp_update_BatchUtils
 * Method:    patchApk
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_smartapp_update_BatchUtils_patchApk
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
